### ISSUE TITLE
Any Cursor can be Animated

### ISSUE THREAD

**Issue by alexzielenski** [iJunkie22/xcur2cape#1]
Hi, looking through your source I came across this line: https://github.com/iJunkie22/xcur2cape/blob/fdd4f2567162602ed37b99276038d41ac416096b/xcur2cape.py#L166. 

It seems to imply to me that only cursors which "support" animation will be animated in the converted form. This is not the case. With Mousecape you can animate any cursor to up to 24 frames (I think, that number's probably wrong).

**Comment by iJunkie22** [comment]
Not 100% positive I understand what you are suggesting. Does c5622b06e52e8cdca824cc4e89f580f0cca67f25 resolve what you are talking about?

**Comment by alexzielenski** [comment]
Yup! I meant that if the xcur cursor was animated it should be so in Mousecape even if the original system one is not so. However, there is a hard frame limit of 24 that you should verify.
